# Generated by Django 3.2.8 on 2021-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://cybergisxhub.cigi.illinois.edu/wp-content/uploads/2020/10/Portrait_Placeholder.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Denver, CO', max_length=250),
        ),
    ]
