# Generated by Django 3.2.8 on 2021-11-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAdmin',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.profile')),
            ],
            bases=('main_app.profile',),
        ),
    ]
